# Generated by Django 2.0 on 2018-02-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_text', models.CharField(max_length=500)),
                ('writer_nickname', models.CharField(max_length=50)),
                ('entry_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
